#controller_manager_ns: controller_manager
controller_list:
 - name: position_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:  
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
initial:  # Define initial robot poses.
  - group: rv6l_planning_group
    pose: zero