rv6l_planning_group:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  position_only_ik: ARE
  #kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  solve_type: Speed    #Distance not working

#rv6l_planning_group:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 5.0
#  solve_type: Speed
#  position_only_ik: True
  